[serviceweaver]
binary = "./iris.exe"

[single]
listeners.lisUser = {address = "localhost:9001"}
listeners.lisCompany = {address = "localhost:9002"}

[multi]
listeners.lisUser = {address = "localhost:9001"}
listeners.lisCompany = {address = "localhost:9002"}
